# Generated by Django 5.0.3 on 2024-03-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Development', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
